### ISSUE TITLE
Binary Sensor doesn't work starting from 0.91

### ISSUE THREAD

**Issue by jokerigno** [custom-components/binary_sensor.hadockermon#8]
Starting from few weeks component stopped working.

Here's the message on HA Log:

Integration hadockermon not found when trying to verify its switch platform.
Integration hadockermon not found when trying to verify its binary_sensor platform.

**Comment by romanpeters** [comment]
I have exactly the same problem as @jokerigno.

**Comment by ludeeus** [comment]
add a blank `__init__.py` file

**Comment by jokerigno** [comment]
Well, that was pretty easy.

**Comment by ludeeus** [comment]
Yeah, that works, but this integration is in need of an overhaul..
